#!/usr/bin/with-contenv bash

declare -A SNIBOX_CONF
SNIBOX_CONF[DB_NAME]=${DB_NAME:-snibox}
SNIBOX_CONF[DB_USER]=${DB_USER:-postgres}
SNIBOX_CONF[DB_PASS]=${DB_PASS:-}
SNIBOX_CONF[DB_HOST]=${DB_HOST:-postgres}
SNIBOX_CONF[DB_PORT]=${DB_PORT:-5432}
SNIBOX_CONF[MAILGUN_SMTP_PORT]=${MAILGUN_SMTP_PORT:-587}
SNIBOX_CONF[MAILGUN_SMTP_SERVER]=${MAILGUN_SMTP_SERVER:-smtp.mailgun.org}
SNIBOX_CONF[MAILGUN_SMTP_LOGIN]=${MAILGUN_SMTP_LOGIN:-}
SNIBOX_CONF[MAILGUN_SMTP_PASSWORD]=${MAILGUN_SMTP_PASSWORD:-}
SNIBOX_CONF[MAILGUN_API_KEY]=${MAILGUN_API_KEY:-}
SNIBOX_CONF[MAILGUN_DOMAIN]=${MAILGUN_DOMAIN:-}
SNIBOX_CONF[MAILGUN_PUBLIC_KEY]=${MAILGUN_PUBLIC_KEY:-}

# persist env variables
if [ ! -f "/config/.env" ]; then
	cp /app/snibox/.env.production.sample /config/.env
	SECRET=$(cd /app/snibox && /usr/local/ruby/bin/ruby /app/snibox/bin/rake secret)

	sed -i 's|paste_your_key|'$SECRET'|g' /config/.env

	for KEY in "${!SNIBOX_CONF[@]}"; do \
	if [[ ${SNIBOX_CONF[$KEY]} == "" ]]; then \
	:
	else sed -i 's|'$KEY'=.*$|'$KEY'='${SNIBOX_CONF[$KEY]}'|g' /config/.env
	fi
	done
fi

if [ ! -f "/app/snibox/.env" ]; then
	ln -s /config/.env /app/snibox/.env
fi

if [ ! -f "/etc/nginx/conf.d/default.conf" ]; then
	rm /etc/nginx/sites-enabled/default
	mv /defaults/default.conf /etc/nginx/conf.d/default.conf
fi

cd /app/snibox || exit

RAILS_ENV=production /usr/local/ruby/bin/ruby ./bin/rake db:setup
RAILS_ENV=production /usr/local/ruby/bin/ruby ./bin/rake assets:precompile

# permissions
chown -R abc:abc \
	/app/snibox \
	/config
