#!/usr/bin/with-contenv bash

DB_NAME=${DB_NAME:-snibox}
DB_USER=${DB_USER:-postgres}
DB_PASS=${DB_PASS:-}
DB_HOST=${DB_HOST:-postgres}
DB_PORT=${DB_PORT:-5432}
MAILGUN_SMTP_PORT=${MAILGUN_SMTP_PORT:-587}
MAILGUN_SMTP_SERVER=${MAILGUN_SMTP_SERVER:-smtp.mailgun.org}
MAILGUN_SMTP_LOGIN=${MAILGUN_SMTP_LOGIN:-}
MAILGUN_SMTP_PASSWORD=${MAILGUN_SMTP_PASSWORD:-}
MAILGUN_API_KEY=${MAILGUN_API_KEY:-}
MAILGUN_DOMAIN=${MAILGUN_DOMAIN:-}
MAILGUN_PUBLIC_KEY=${MAILGUN_PUBLIC_KEY:-}

# persist env variables
if [ ! -f "/config/.env" ]; then
	cp /app/snibox/.env.production.sample /config/.env
	SECRET=$(cd /app/snibox && /usr/local/ruby/bin/ruby /app/snibox/bin/rake secret)

	sed -i 's|paste_your_key|'$SECRET'|g' /config/.env
	sed -i 's|DB_NAME=postgres|DB_NAME='$DB_NAME'|g' /config/.env
	sed -i 's|DB_USER=postgres|DB_USER='$DB_USER'|g' /config/.env
	sed -i 's|DB_PASS=|DB_PASS='$DB_PASS'|g' /config/.env
	sed -i 's|DB_HOST=database|DB_HOST='$DB_HOST'|g' /config/.env
	sed -i 's|DB_PORT=5432|DB_PORT='$DB_PORT'|g' /config/.env
	sed -i 's|MAILGUN_SMTP_PORT=587|MAILGUN_SMTP_PORT='$MAILGUN_SMTP_PORT'|g' /config/.env
	sed -i 's|MAILGUN_SMTP_SERVER=smtp.mailgun.org|MAILGUN_SMTP_SERVER='$MAILGUN_SMTP_SERVER'|g' /config/.env
	sed -i 's|MAILGUN_SMTP_LOGIN=|MAILGUN_SMTP_LOGIN='$MAILGUN_SMTP_LOGIN'|g' /config/.env
	sed -i 's|MAILGUN_SMTP_PASSWORD=|MAILGUN_SMTP_PASSWORD='$MAILGUN_SMTP_PASSWORD'|g' /config/.env
	sed -i 's|MAILGUN_API_KEY=|MAILGUN_API_KEY='$MAILGUN_API_KEY'|g' /config/.env
	sed -i 's|MAILGUN_DOMAIN=|MAILGUN_DOMAIN='$MAILGUN_DOMAIN'|g' /config/.env
	sed -i 's|MAILGUN_PUBLIC_KEY=|MAILGUN_PUBLIC_KEY='$MAILGUN_PUBLIC_KEY'|g' /config/.env
fi

if [ ! -f "/app/snibox/.env" ]; then
	ln -s /config/.env /app/snibox/.env
fi

if [ ! -f "/etc/nginx/conf.d/default.conf" ]; then
	mv /defaults/default.conf /etc/nginx/conf.d/default.conf
fi

cd /app/snibox || exit

RAILS_ENV=production /usr/local/ruby/bin/ruby ./bin/rake db:setup
RAILS_ENV=production /usr/local/ruby/bin/ruby ./bin/rake assets:precompile

# permissions
chown -R abc:abc \
	/app/snibox \
	/config
